language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION="2.1" GUZZLE_VERSION="3.1"
  - SYMFONY_VERSION="2.*" GUZZLE_VERSION="3.1"
  - SYMFONY_VERSION="2.1" GUZZLE_VERSION="3.*"
  - SYMFONY_VERSION="2.*" GUZZLE_VERSION="3.*"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update
  - composer require guzzle/http:${GUZZLE_VERSION} --no-update
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 vendor/omnipay/omnipay/src/Omnipay/Adyen && vendor/bin/phpunit vendor/omnipay/omnipay/src/Omnipay/Adyen --coverage-text

script: vendor/bin/phpcs --standard=PSR2 vendor/omnipay/omnipay/tests/Omnipay/Adyen && vendor/bin/phpunit vendor/omnipay/omnipay/tests/Omnipay/Adyen --coverage-text
